version: '3.8'

services:

  website:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "siapp.app:create_app()"
    volumes:
      - .:/siapp
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=siapp/app.py
      - FLASK_ENV=development

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A siapp.blueprints.contact.tasks worker --loglevel=info
    env_file:
      - '.env'
    volumes:
      - '.:/siapp'

volumes:
  redis:
  